### ISSUE TITLE
Build: lost FindVala.cmake

### ISSUE THREAD

**Issue by yetist** [jendamarek/scripture#1]
Build error:
> -- Checking for modules 'gtk+-3.0;gee-0.8;granite;webkit2gtk-4.0>=2.14.1;sqlite3>=3.5.9'
> --   Found gtk+-3.0, version 3.22.16
> --   Found gee-0.8, version 0.20.0
> --   Found granite, version 0.4.1
> --   Found webkit2gtk-4.0, version 2.16.4
> --   Found sqlite3, version 3.19.3
> CMake Error at CMakeLists.txt:31 (find_package):
>   By not providing "FindVala.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Vala", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Vala" with any of
>   the following names:
> 
>     ValaConfig.cmake
>     vala-config.cmake
> 
>   Add the installation prefix of "Vala" to CMAKE_PREFIX_PATH or set
>   "Vala_DIR" to a directory containing one of the above files.  If "Vala"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> 
Maybe lost some cmake files?

**Comment by jendamarek** [comment]
Are you building on elementary os?
I think elementary-sdk package is required to build. Maybe that could be the problem.

**Comment by yetist** [comment]
I build it on Archlinux，I think you should create cmake directory, and include [findvala.cmake](https://github.com/jakobwesthoff/Vala_CMake) in it.

Or you can try to use [meson](http://mesonbuild.com/index.html) for build.

**Comment by yetist** [comment]
OK, after add FindVala.cmake, you sould apply this patch:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3453e3e..1089e80 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -29,11 +29,9 @@ link_libraries(${DEPS_LIBRARIES} -lm)
 link_directories(${DEPS_LIBRARY_DIRS})
 
 find_package(Vala REQUIRED)
-include(ValaVersion)
-ensure_vala_version("0.16" MINIMUM)
+include(${VALA_USE_FILE})
 
-include(ValaPrecompile)
-vala_precompile(VALA_C ${EXEC_NAME}
+vala_precompile(VALA_C
    src/Main.vala
    src/Window.vala
    src/Widgets/ChapterSelect.vala
@@ -57,7 +55,7 @@ PACKAGES
    gtk+-3.0
    gee-0.8
    granite
-   webkit2gtk-4.0>=2.14.1
+   webkit2gtk-4.0
    sqlite3
 )
 

```

**Comment by jendamarek** [comment]
should be there now, i'm closing the issue
